//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.21 at 03:44:38 PM CEST 
//


package com.exchange.client.model.callback;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for feesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="feesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="transactionAmount" type="{http://asxgw.com/Schema/V2/Callback}amountType" minOccurs="0"/>
 *         &lt;element name="transactionCurrency" type="{http://asxgw.com/Schema/V2/Callback}currencyType" minOccurs="0"/>
 *         &lt;element name="providerFeeAmount" type="{http://asxgw.com/Schema/V2/Callback}amountType" minOccurs="0"/>
 *         &lt;element name="providerFeeCurrency" type="{http://asxgw.com/Schema/V2/Callback}currencyType" minOccurs="0"/>
 *         &lt;element name="providerPayoutAmount" type="{http://asxgw.com/Schema/V2/Callback}amountType" minOccurs="0"/>
 *         &lt;element name="providerPayoutCurrency" type="{http://asxgw.com/Schema/V2/Callback}currencyType" minOccurs="0"/>
 *         &lt;element name="exchangeFeeAmount" type="{http://asxgw.com/Schema/V2/Callback}amountType" minOccurs="0"/>
 *         &lt;element name="exchangeFeeCurrency" type="{http://asxgw.com/Schema/V2/Callback}currencyType" minOccurs="0"/>
 *         &lt;element name="exchangePayoutAmount" type="{http://asxgw.com/Schema/V2/Callback}amountType" minOccurs="0"/>
 *         &lt;element name="exchangePayoutCurrency" type="{http://asxgw.com/Schema/V2/Callback}currencyType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "feesType", propOrder = {
    "transactionAmount",
    "transactionCurrency",
    "providerFeeAmount",
    "providerFeeCurrency",
    "providerPayoutAmount",
    "providerPayoutCurrency",
    "exchangeFeeAmount",
    "exchangeFeeCurrency",
    "exchangePayoutAmount",
    "exchangePayoutCurrency"
})
public class FeesType {

    protected BigDecimal transactionAmount;
    protected String transactionCurrency;
    protected BigDecimal providerFeeAmount;
    protected String providerFeeCurrency;
    protected BigDecimal providerPayoutAmount;
    protected String providerPayoutCurrency;
    protected BigDecimal exchangeFeeAmount;
    protected String exchangeFeeCurrency;
    protected BigDecimal exchangePayoutAmount;
    protected String exchangePayoutCurrency;

    /**
     * Default no-arg constructor
     * 
     */
    public FeesType() {
        super();
    }

    /**
     * Fully-initialising value constructor
     * 
     */
    public FeesType(final BigDecimal transactionAmount, final String transactionCurrency, final BigDecimal providerFeeAmount, final String providerFeeCurrency, final BigDecimal providerPayoutAmount, final String providerPayoutCurrency, final BigDecimal exchangeFeeAmount, final String exchangeFeeCurrency, final BigDecimal exchangePayoutAmount, final String exchangePayoutCurrency) {
        this.transactionAmount = transactionAmount;
        this.transactionCurrency = transactionCurrency;
        this.providerFeeAmount = providerFeeAmount;
        this.providerFeeCurrency = providerFeeCurrency;
        this.providerPayoutAmount = providerPayoutAmount;
        this.providerPayoutCurrency = providerPayoutCurrency;
        this.exchangeFeeAmount = exchangeFeeAmount;
        this.exchangeFeeCurrency = exchangeFeeCurrency;
        this.exchangePayoutAmount = exchangePayoutAmount;
        this.exchangePayoutCurrency = exchangePayoutCurrency;
    }

    /**
     * Gets the value of the transactionAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTransactionAmount() {
        return transactionAmount;
    }

    /**
     * Sets the value of the transactionAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTransactionAmount(BigDecimal value) {
        this.transactionAmount = value;
    }

    /**
     * Gets the value of the transactionCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionCurrency() {
        return transactionCurrency;
    }

    /**
     * Sets the value of the transactionCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionCurrency(String value) {
        this.transactionCurrency = value;
    }

    /**
     * Gets the value of the providerFeeAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getProviderFeeAmount() {
        return providerFeeAmount;
    }

    /**
     * Sets the value of the providerFeeAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setProviderFeeAmount(BigDecimal value) {
        this.providerFeeAmount = value;
    }

    /**
     * Gets the value of the providerFeeCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProviderFeeCurrency() {
        return providerFeeCurrency;
    }

    /**
     * Sets the value of the providerFeeCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProviderFeeCurrency(String value) {
        this.providerFeeCurrency = value;
    }

    /**
     * Gets the value of the providerPayoutAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getProviderPayoutAmount() {
        return providerPayoutAmount;
    }

    /**
     * Sets the value of the providerPayoutAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setProviderPayoutAmount(BigDecimal value) {
        this.providerPayoutAmount = value;
    }

    /**
     * Gets the value of the providerPayoutCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProviderPayoutCurrency() {
        return providerPayoutCurrency;
    }

    /**
     * Sets the value of the providerPayoutCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProviderPayoutCurrency(String value) {
        this.providerPayoutCurrency = value;
    }

    /**
     * Gets the value of the exchangeFeeAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getExchangeFeeAmount() {
        return exchangeFeeAmount;
    }

    /**
     * Sets the value of the exchangeFeeAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setExchangeFeeAmount(BigDecimal value) {
        this.exchangeFeeAmount = value;
    }

    /**
     * Gets the value of the exchangeFeeCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExchangeFeeCurrency() {
        return exchangeFeeCurrency;
    }

    /**
     * Sets the value of the exchangeFeeCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExchangeFeeCurrency(String value) {
        this.exchangeFeeCurrency = value;
    }

    /**
     * Gets the value of the exchangePayoutAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getExchangePayoutAmount() {
        return exchangePayoutAmount;
    }

    /**
     * Sets the value of the exchangePayoutAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setExchangePayoutAmount(BigDecimal value) {
        this.exchangePayoutAmount = value;
    }

    /**
     * Gets the value of the exchangePayoutCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExchangePayoutCurrency() {
        return exchangePayoutCurrency;
    }

    /**
     * Sets the value of the exchangePayoutCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExchangePayoutCurrency(String value) {
        this.exchangePayoutCurrency = value;
    }

}
